[project]
name = "paperbuddy"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "crewai>=0.30",
    "docling>=2.0",
    "chromadb>=0.5",
    "sentence-transformers>=3.0",
    "fastapi>=0.110",
    "uvicorn[standard]>=0.29",
]